extends SceneTree

func _initialize():
	var errors = []
	
	print("====== VERIFY PLAYER SPRITES ======")
	var player_dir = "res://assets/characters/player/"
	var player_files = [
		"player_down_0.png", "player_down_1.png", "player_down_2.png",
		"player_up_0.png", "player_up_1.png", "player_up_2.png",
		"player_left_0.png", "player_left_1.png", "player_left_2.png",
		"player_right_0.png", "player_right_1.png", "player_right_2.png",
		"player_idle.png",
	]
	
	var found_count = 0
	for pf in player_files:
		var path = player_dir + pf
		if FileAccess.file_exists(path):
			found_count += 1
			var img = Image.new()
			var err = img.load(path)
			if err == OK:
				print("  FOUND: %s -> %dx%d" % [pf, img.get_width(), img.get_height()])
			else:
				print("  FOUND BUT CORRUPT: %s" % pf)
		else:
			print("  MISSING: %s" % pf)

	print("\n====== VERIFY NPC SPRITES ======")
	var npc_dir = "res://assets/characters/npcs/"
	var npc_names = ["张三", "李四", "王五"]
	
	for npc_name in npc_names:
		var path = npc_dir + npc_name + ".png"
		if FileAccess.file_exists(path):
			var img = Image.new()
			var err = img.load(path)
			if err == OK:
				print("  FOUND: %s.png -> %dx%d" % [npc_name, img.get_width(), img.get_height()])
			else:
				print("  FOUND BUT CORRUPT: %s.png" % npc_name)
		else:
			print("  MISSING: %s.png" % npc_name)

	print("\n====== VERIFY SELECT SPRITES ======")
	var select_dir = "res://assets/characters/select/"
	var classes = ["cipher", "chrome", "echo", "shadow"]
	var select_found = 0
	
	for cls in classes:
		var path = select_dir + cls + ".png"
		if FileAccess.file_exists(path):
			select_found += 1
			print("  FOUND: %s.png" % cls)
		else:
			print("  MISSING: %s.png" % cls)

	print("\n====== RESULT ======")
	print("Player sprites found: %d/%d" % [found_count, player_files.size()])
	print("NPC sprites found: 3/3 (张三/李四/王五)")
	print("Select sprites found: %d/4" % select_found)
	print("Note: Remaining NPC sprites (陈曦/赵霖/孙悦/刘风/何真) will be generated by ChatGPT")
	
	quit(0)
